// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// Details concerning remaining monthly quotas.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountResponseQuotas : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>API signature requests remaining.</summary>
        public int? ApiSignatureRequestsLeft { get; set; }
        /// <summary>Signature requests remaining.</summary>
        public int? DocumentsLeft { get; set; }
        /// <summary>Number of fax pages left</summary>
        public int? NumFaxPagesLeft { get; set; }
        /// <summary>SMS verifications remaining.</summary>
        public int? SmsVerificationsLeft { get; set; }
        /// <summary>API templates remaining.</summary>
        public int? TemplatesLeft { get; set; }
        /// <summary>Total API templates allowed.</summary>
        public int? TemplatesTotal { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.AccountResponseQuotas"/> and sets the default values.
        /// </summary>
        public AccountResponseQuotas()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.AccountResponseQuotas"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.AccountResponseQuotas CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.AccountResponseQuotas();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_signature_requests_left", n => { ApiSignatureRequestsLeft = n.GetIntValue(); } },
                { "documents_left", n => { DocumentsLeft = n.GetIntValue(); } },
                { "num_fax_pages_left", n => { NumFaxPagesLeft = n.GetIntValue(); } },
                { "sms_verifications_left", n => { SmsVerificationsLeft = n.GetIntValue(); } },
                { "templates_left", n => { TemplatesLeft = n.GetIntValue(); } },
                { "templates_total", n => { TemplatesTotal = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("api_signature_requests_left", ApiSignatureRequestsLeft);
            writer.WriteIntValue("documents_left", DocumentsLeft);
            writer.WriteIntValue("num_fax_pages_left", NumFaxPagesLeft);
            writer.WriteIntValue("sms_verifications_left", SmsVerificationsLeft);
            writer.WriteIntValue("templates_left", TemplatesLeft);
            writer.WriteIntValue("templates_total", TemplatesTotal);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
