// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApiAppCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL at which the ApiApp should receive event callbacks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallbackUrl { get; set; }
#nullable restore
#else
        public string CallbackUrl { get; set; }
#endif
        /// <summary>An image file to use as a custom logo in embedded contexts. (Only applies to some API plans)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? CustomLogoFile { get; set; }
#nullable restore
#else
        public byte[] CustomLogoFile { get; set; }
#endif
        /// <summary>The domain names the ApiApp will be associated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Domains { get; set; }
#nullable restore
#else
        public List<string> Domains { get; set; }
#endif
        /// <summary>The name you want to assign to the ApiApp.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>OAuth related parameters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubOAuth? Oauth { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubOAuth Oauth { get; set; }
#endif
        /// <summary>Additional options supported by API App.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubOptions? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubOptions Options { get; set; }
#endif
        /// <summary>An array of elements and values serialized to a string, to be used to customize the app&apos;s signer page. (Only applies to some API plans)Take a look at our [white labeling guide](https://developers.hellosign.com/api/reference/premium-branding/) to learn more.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions? WhiteLabelingOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions WhiteLabelingOptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.ApiAppCreateRequest"/> and sets the default values.
        /// </summary>
        public ApiAppCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.ApiAppCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.ApiAppCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.ApiAppCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "callback_url", n => { CallbackUrl = n.GetStringValue(); } },
                { "custom_logo_file", n => { CustomLogoFile = n.GetByteArrayValue(); } },
                { "domains", n => { Domains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "oauth", n => { Oauth = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubOAuth>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubOAuth.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubOptions.CreateFromDiscriminatorValue); } },
                { "white_labeling_options", n => { WhiteLabelingOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("callback_url", CallbackUrl);
            writer.WriteByteArrayValue("custom_logo_file", CustomLogoFile);
            writer.WriteCollectionOfPrimitiveValues<string>("domains", Domains);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubOAuth>("oauth", Oauth);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubOptions>("options", Options);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions>("white_labeling_options", WhiteLabelingOptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
