// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FaxLineAreaCodeGetProvinceParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AB")]
        #pragma warning disable CS1591
        Ab,
        #pragma warning restore CS1591
        [EnumMember(Value = "BC")]
        #pragma warning disable CS1591
        Bc,
        #pragma warning restore CS1591
        [EnumMember(Value = "MB")]
        #pragma warning disable CS1591
        Mb,
        #pragma warning restore CS1591
        [EnumMember(Value = "NB")]
        #pragma warning disable CS1591
        Nb,
        #pragma warning restore CS1591
        [EnumMember(Value = "NL")]
        #pragma warning disable CS1591
        Nl,
        #pragma warning restore CS1591
        [EnumMember(Value = "NT")]
        #pragma warning disable CS1591
        Nt,
        #pragma warning restore CS1591
        [EnumMember(Value = "NS")]
        #pragma warning disable CS1591
        Ns,
        #pragma warning restore CS1591
        [EnumMember(Value = "NU")]
        #pragma warning disable CS1591
        Nu,
        #pragma warning restore CS1591
        [EnumMember(Value = "ON")]
        #pragma warning disable CS1591
        On,
        #pragma warning restore CS1591
        [EnumMember(Value = "PE")]
        #pragma warning disable CS1591
        Pe,
        #pragma warning restore CS1591
        [EnumMember(Value = "QC")]
        #pragma warning disable CS1591
        Qc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SK")]
        #pragma warning disable CS1591
        Sk,
        #pragma warning restore CS1591
        [EnumMember(Value = "YT")]
        #pragma warning disable CS1591
        Yt,
        #pragma warning restore CS1591
    }
}
