// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReportResponseReportTypeItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "user_activity")]
        #pragma warning disable CS1591
        UserActivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "document_status")]
        #pragma warning disable CS1591
        DocumentStatus,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms_activity")]
        #pragma warning disable CS1591
        SmsActivity,
        #pragma warning restore CS1591
        [EnumMember(Value = "fax_usage")]
        #pragma warning disable CS1591
        FaxUsage,
        #pragma warning restore CS1591
    }
}
