// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SignatureRequestCreateEmbeddedRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allows signers to decline to sign a document if `true`. Defaults to `false`.</summary>
        public bool? AllowDecline { get; set; }
        /// <summary>Allows signers to reassign their signature requests to other signers if set to `true`. Defaults to `false`.**NOTE:** Only available for Premium plan.</summary>
        public bool? AllowReassign { get; set; }
        /// <summary>A list describing the attachments</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubAttachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubAttachment> Attachments { get; set; }
#endif
        /// <summary>The email addresses that should be CCed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CcEmailAddresses { get; set; }
#nullable restore
#else
        public List<string> CcEmailAddresses { get; set; }
#endif
        /// <summary>Client id of the app you&apos;re using to create this embedded signature request. Used for security purposes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>When used together with merge fields, `custom_fields` allows users to add pre-filled data to their signature requests.Pre-filled data can be used with &quot;send-once&quot; signature requests by adding merge fields with `form_fields_per_document` or [Text Tags](https://app.hellosign.com/api/textTagsWalkthrough#TextTagIntro) while passing values back with `custom_fields` together in one API call.For using pre-filled on repeatable signature requests, merge fields are added to templates in the Dropbox Sign UI or by calling [/template/create_embedded_draft](/api/reference/operation/templateCreateEmbeddedDraft) and then passing `custom_fields` on subsequent signature requests referencing that template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField> CustomFields { get; set; }
#endif
        /// <summary>When the signature request will expire. Unsigned signatures will be moved to the expired status, and no longer signable. See [Signature Request Expiration Date](https://developers.hellosign.com/docs/signature-request/expiration/) for details.</summary>
        public int? ExpiresAt { get; set; }
        /// <summary>This allows the requester to specify field options for a signature request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions? FieldOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions FieldOptions { get; set; }
#endif
        /// <summary>Use `files[]` to indicate the uploaded file(s) to send for signature.This endpoint requires either **files** or **file_urls[]**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<byte[]>? Files { get; set; }
#nullable restore
#else
        public List<byte[]> Files { get; set; }
#endif
        /// <summary>Use `file_urls[]` to have Dropbox Sign download the file(s) to send for signature.This endpoint requires either **files** or **file_urls[]**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FileUrls { get; set; }
#nullable restore
#else
        public List<string> FileUrls { get; set; }
#endif
        /// <summary>Group information for fields defined in `form_fields_per_document`. String-indexed JSON array with `group_label` and `requirement` keys. `form_fields_per_document` must contain fields referencing a group defined in `form_field_groups`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldGroup>? FormFieldGroups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldGroup> FormFieldGroups { get; set; }
#endif
        /// <summary>Conditional Logic rules for fields defined in `form_fields_per_document`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRule>? FormFieldRules { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRule> FormFieldRules { get; set; }
#endif
        /// <summary>&quot;The fields that should appear on the document, expressed as an array of objects. (For more details you can read about it here: [Using Form Fields per Document](/docs/openapi/form-fields-per-document).)**NOTE:** Fields like **text**, **dropdown**, **checkbox**, **radio**, and **hyperlink** have additional required and optional parameters. Check out the list of [additional parameters](/api/reference/constants/#form-fields-per-document) for these field types.* Text Field use `SubFormFieldsPerDocumentText`* Dropdown Field use `SubFormFieldsPerDocumentDropdown`* Hyperlink Field use `SubFormFieldsPerDocumentHyperlink`* Checkbox Field use `SubFormFieldsPerDocumentCheckbox`* Radio Field use `SubFormFieldsPerDocumentRadio`* Signature Field use `SubFormFieldsPerDocumentSignature`* Date Signed Field use `SubFormFieldsPerDocumentDateSigned`* Initials Field use `SubFormFieldsPerDocumentInitials`* Text Merge Field use `SubFormFieldsPerDocumentTextMerge`* Checkbox Merge Field use `SubFormFieldsPerDocumentCheckboxMerge`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase>? FormFieldsPerDocument { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase> FormFieldsPerDocument { get; set; }
#endif
        /// <summary>Add Grouped Signers to your Signature Request.This endpoint requires either **signers** or **grouped_signers**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestGroupedSigners>? GroupedSigners { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestGroupedSigners> GroupedSigners { get; set; }
#endif
        /// <summary>Enables automatic Text Tag removal when set to true.**NOTE:** Removing text tags this way can cause unwanted clipping. We recommend leaving this setting on `false` and instead hiding your text tags using white text or a similar approach. See the [Text Tags Walkthrough](https://app.hellosign.com/api/textTagsWalkthrough#TextTagIntro) for more information.</summary>
        public bool? HideTextTags { get; set; }
        /// <summary>The custom message in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Key-value data that should be attached to the signature request. This metadata is included in all API responses and events involving the signature request. For example, use the metadata field to store a signer&apos;s order number for look up when receiving events for the signature request.Each request can include up to 10 metadata keys (or 50 nested metadata keys), with key names up to 40 characters long and values up to 1000 characters long.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest_metadata Metadata { get; set; }
#endif
        /// <summary>Controls whether [auto fill fields](https://faq.hellosign.com/hc/en-us/articles/360051467511-Auto-Fill-Fields) can automatically populate a signer&apos;s information during signing.**NOTE:** Keep your signer&apos;s information safe by ensuring that the _signer on your signature request is the intended party_ before using this feature.</summary>
        public bool? PopulateAutoFillFields { get; set; }
        /// <summary>Configuration options for modifying the settings of the signer application. Supports changing the form view behavior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience? SignerExperience { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience SignerExperience { get; set; }
#endif
        /// <summary>Add Signers to your Signature Request.This endpoint requires either **signers** or **grouped_signers**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestSigner>? Signers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestSigner> Signers { get; set; }
#endif
        /// <summary>This allows the requester to specify the types allowed for creating a signature.**NOTE:** If `signing_options` are not defined in the request, the allowed types will default to those specified in the account settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions? SigningOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions SigningOptions { get; set; }
#endif
        /// <summary>The subject in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Whether this is a test, the signature request will not be legally binding if set to `true`. Defaults to `false`.</summary>
        public bool? TestMode { get; set; }
        /// <summary>The title you want to assign to the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Send with a value of `true` if you wish to enable [Text Tags](https://app.hellosign.com/api/textTagsWalkthrough#TextTagIntro) parsing in your document. Defaults to disabled, or `false`.</summary>
        public bool? UseTextTags { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest"/> and sets the default values.
        /// </summary>
        public SignatureRequestCreateEmbeddedRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_decline", n => { AllowDecline = n.GetBoolValue(); } },
                { "allow_reassign", n => { AllowReassign = n.GetBoolValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubAttachment>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubAttachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cc_email_addresses", n => { CcEmailAddresses = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "expires_at", n => { ExpiresAt = n.GetIntValue(); } },
                { "field_options", n => { FieldOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions.CreateFromDiscriminatorValue); } },
                { "file_urls", n => { FileUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "files", n => { Files = n.GetCollectionOfPrimitiveValues<byte[]>()?.AsList(); } },
                { "form_field_groups", n => { FormFieldGroups = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldGroup>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldGroup.CreateFromDiscriminatorValue)?.AsList(); } },
                { "form_field_rules", n => { FormFieldRules = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRule>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "form_fields_per_document", n => { FormFieldsPerDocument = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "grouped_signers", n => { GroupedSigners = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestGroupedSigners>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestGroupedSigners.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hide_text_tags", n => { HideTextTags = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest_metadata.CreateFromDiscriminatorValue); } },
                { "populate_auto_fill_fields", n => { PopulateAutoFillFields = n.GetBoolValue(); } },
                { "signer_experience", n => { SignerExperience = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience.CreateFromDiscriminatorValue); } },
                { "signers", n => { Signers = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestSigner>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestSigner.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signing_options", n => { SigningOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions.CreateFromDiscriminatorValue); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "test_mode", n => { TestMode = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "use_text_tags", n => { UseTextTags = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_decline", AllowDecline);
            writer.WriteBoolValue("allow_reassign", AllowReassign);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubAttachment>("attachments", Attachments);
            writer.WriteCollectionOfPrimitiveValues<string>("cc_email_addresses", CcEmailAddresses);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>("custom_fields", CustomFields);
            writer.WriteIntValue("expires_at", ExpiresAt);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions>("field_options", FieldOptions);
            writer.WriteCollectionOfPrimitiveValues<byte[]>("files", Files);
            writer.WriteCollectionOfPrimitiveValues<string>("file_urls", FileUrls);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldGroup>("form_field_groups", FormFieldGroups);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRule>("form_field_rules", FormFieldRules);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase>("form_fields_per_document", FormFieldsPerDocument);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestGroupedSigners>("grouped_signers", GroupedSigners);
            writer.WriteBoolValue("hide_text_tags", HideTextTags);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestCreateEmbeddedRequest_metadata>("metadata", Metadata);
            writer.WriteBoolValue("populate_auto_fill_fields", PopulateAutoFillFields);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience>("signer_experience", SignerExperience);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestSigner>("signers", Signers);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>("signing_options", SigningOptions);
            writer.WriteStringValue("subject", Subject);
            writer.WriteBoolValue("test_mode", TestMode);
            writer.WriteStringValue("title", Title);
            writer.WriteBoolValue("use_text_tags", UseTextTags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
