// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// An array of signature objects, 1 for each signer.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignatureRequestResponseSignatures : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The reason provided by the signer for declining the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeclineReason { get; set; }
#nullable restore
#else
        public string DeclineReason { get; set; }
#endif
        /// <summary>Error message pertaining to this signer, or null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Boolean to indicate whether this signature requires a PIN to access.</summary>
        public bool? HasPin { get; set; }
        /// <summary>Boolean to indicate whether this signature has SMS authentication enabled.</summary>
        public bool? HasSmsAuth { get; set; }
        /// <summary>Boolean to indicate whether this signature has SMS delivery enabled.</summary>
        public bool? HasSmsDelivery { get; set; }
        /// <summary>The time the last reminder email was sent to the signer or null.</summary>
        public int? LastRemindedAt { get; set; }
        /// <summary>The time that the document was last viewed by this signer or null.</summary>
        public int? LastViewedAt { get; set; }
        /// <summary>If signer order is assigned this is the 0-based index for this signer.</summary>
        public int? Order { get; set; }
        /// <summary>Email address of original signer who reassigned to this signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReassignedBy { get; set; }
#nullable restore
#else
        public string ReassignedBy { get; set; }
#endif
        /// <summary>Previous signature identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReassignedFrom { get; set; }
#nullable restore
#else
        public string ReassignedFrom { get; set; }
#endif
        /// <summary>Reason provided by original signer who reassigned to this signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReassignmentReason { get; set; }
#nullable restore
#else
        public string ReassignmentReason { get; set; }
#endif
        /// <summary>Signature identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatureId { get; set; }
#nullable restore
#else
        public string SignatureId { get; set; }
#endif
        /// <summary>Time that the document was signed or null.</summary>
        public int? SignedAt { get; set; }
        /// <summary>The email address of the signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignerEmailAddress { get; set; }
#nullable restore
#else
        public string SignerEmailAddress { get; set; }
#endif
        /// <summary>Signer Group GUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignerGroupGuid { get; set; }
#nullable restore
#else
        public string SignerGroupGuid { get; set; }
#endif
        /// <summary>The name of the signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignerName { get; set; }
#nullable restore
#else
        public string SignerName { get; set; }
#endif
        /// <summary>The role of the signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignerRole { get; set; }
#nullable restore
#else
        public string SignerRole { get; set; }
#endif
        /// <summary>The SMS phone number used for authentication or signature request delivery.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmsPhoneNumber { get; set; }
#nullable restore
#else
        public string SmsPhoneNumber { get; set; }
#endif
        /// <summary>&quot;The current status of the signature. eg: awaiting_signature, signed, declined.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusCode { get; set; }
#nullable restore
#else
        public string StatusCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures"/> and sets the default values.
        /// </summary>
        public SignatureRequestResponseSignatures()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "decline_reason", n => { DeclineReason = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "has_pin", n => { HasPin = n.GetBoolValue(); } },
                { "has_sms_auth", n => { HasSmsAuth = n.GetBoolValue(); } },
                { "has_sms_delivery", n => { HasSmsDelivery = n.GetBoolValue(); } },
                { "last_reminded_at", n => { LastRemindedAt = n.GetIntValue(); } },
                { "last_viewed_at", n => { LastViewedAt = n.GetIntValue(); } },
                { "order", n => { Order = n.GetIntValue(); } },
                { "reassigned_by", n => { ReassignedBy = n.GetStringValue(); } },
                { "reassigned_from", n => { ReassignedFrom = n.GetStringValue(); } },
                { "reassignment_reason", n => { ReassignmentReason = n.GetStringValue(); } },
                { "signature_id", n => { SignatureId = n.GetStringValue(); } },
                { "signed_at", n => { SignedAt = n.GetIntValue(); } },
                { "signer_email_address", n => { SignerEmailAddress = n.GetStringValue(); } },
                { "signer_group_guid", n => { SignerGroupGuid = n.GetStringValue(); } },
                { "signer_name", n => { SignerName = n.GetStringValue(); } },
                { "signer_role", n => { SignerRole = n.GetStringValue(); } },
                { "sms_phone_number", n => { SmsPhoneNumber = n.GetStringValue(); } },
                { "status_code", n => { StatusCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("decline_reason", DeclineReason);
            writer.WriteStringValue("error", Error);
            writer.WriteBoolValue("has_pin", HasPin);
            writer.WriteBoolValue("has_sms_auth", HasSmsAuth);
            writer.WriteBoolValue("has_sms_delivery", HasSmsDelivery);
            writer.WriteIntValue("last_reminded_at", LastRemindedAt);
            writer.WriteIntValue("last_viewed_at", LastViewedAt);
            writer.WriteIntValue("order", Order);
            writer.WriteStringValue("reassigned_by", ReassignedBy);
            writer.WriteStringValue("reassigned_from", ReassignedFrom);
            writer.WriteStringValue("reassignment_reason", ReassignmentReason);
            writer.WriteStringValue("signature_id", SignatureId);
            writer.WriteIntValue("signed_at", SignedAt);
            writer.WriteStringValue("signer_email_address", SignerEmailAddress);
            writer.WriteStringValue("signer_group_guid", SignerGroupGuid);
            writer.WriteStringValue("signer_name", SignerName);
            writer.WriteStringValue("signer_role", SignerRole);
            writer.WriteStringValue("sms_phone_number", SmsPhoneNumber);
            writer.WriteStringValue("status_code", StatusCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
