// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SignatureRequestBulkCreateEmbeddedWithTemplateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allows signers to decline to sign a document if `true`. Defaults to `false`.</summary>
        public bool? AllowDecline { get; set; }
        /// <summary>Add CC email recipients. Required when a CC role exists for the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>? Ccs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC> Ccs { get; set; }
#endif
        /// <summary>Client id of the app you&apos;re using to create this embedded signature request. Used for security purposes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>When used together with merge fields, `custom_fields` allows users to add pre-filled data to their signature requests.Pre-filled data can be used with &quot;send-once&quot; signature requests by adding merge fields with `form_fields_per_document` or [Text Tags](https://app.hellosign.com/api/textTagsWalkthrough#TextTagIntro) while passing values back with `custom_fields` together in one API call.For using pre-filled on repeatable signature requests, merge fields are added to templates in the Dropbox Sign UI or by calling [/template/create_embedded_draft](/api/reference/operation/templateCreateEmbeddedDraft) and then passing `custom_fields` on subsequent signature requests referencing that template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField> CustomFields { get; set; }
#endif
        /// <summary>The custom message in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Key-value data that should be attached to the signature request. This metadata is included in all API responses and events involving the signature request. For example, use the metadata field to store a signer&apos;s order number for look up when receiving events for the signature request.Each request can include up to 10 metadata keys (or 50 nested metadata keys), with key names up to 40 characters long and values up to 1000 characters long.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest_metadata Metadata { get; set; }
#endif
        /// <summary>&quot;`signer_file` is a CSV file defining values and options for signer fields. Required unless a `signer_list` is used, you may not use both. The CSV can have the following columns:- `name`: the name of the signer filling the role of RoleName- `email_address`: email address of the signer filling the role of RoleName- `pin`: the 4- to 12-character access code that will secure this signer&apos;s signature page (optional)- `sms_phone_number`: An E.164 formatted phone number that will receive a code via SMS to access this signer&apos;s signature page. (optional)    By using the feature, you agree you are responsible for obtaining a signer&apos;s consent to receive text messages from Dropbox Sign related to this signature request and confirm you have obtained such consent from all signers prior to enabling SMS delivery for this signature request. [Learn more](https://faq.hellosign.com/hc/en-us/articles/15815316468877-Dropbox-Sign-SMS-tools-add-on).    **NOTE:** Not available in test mode and requires a Standard plan or higher.- `*_field`: any column with a _field\&quot; suffix will be treated as a custom field (optional)    You may only specify field values here, any other options should be set in the custom_fields request parameter.Example CSV:```name, email_address, pin, company_fieldGeorge, george@example.com, d79a3td, ABC CorpMary, mary@example.com, gd9as5b, 123 LLC```&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? SignerFile { get; set; }
#nullable restore
#else
        public byte[] SignerFile { get; set; }
#endif
        /// <summary>`signer_list` is an array defining values and options for signer fields. Required unless a `signer_file` is used, you may not use both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubBulkSignerList>? SignerList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubBulkSignerList> SignerList { get; set; }
#endif
        /// <summary>The URL you want signers redirected to after they successfully sign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningRedirectUrl { get; set; }
#nullable restore
#else
        public string SigningRedirectUrl { get; set; }
#endif
        /// <summary>The subject in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Use `template_ids` to create a SignatureRequest from one or more templates, in the order in which the template will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TemplateIds { get; set; }
#nullable restore
#else
        public List<string> TemplateIds { get; set; }
#endif
        /// <summary>Whether this is a test, the signature request will not be legally binding if set to `true`. Defaults to `false`.</summary>
        public bool? TestMode { get; set; }
        /// <summary>The title you want to assign to the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest"/> and sets the default values.
        /// </summary>
        public SignatureRequestBulkCreateEmbeddedWithTemplateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_decline", n => { AllowDecline = n.GetBoolValue(); } },
                { "ccs", n => { Ccs = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC.CreateFromDiscriminatorValue)?.AsList(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest_metadata.CreateFromDiscriminatorValue); } },
                { "signer_file", n => { SignerFile = n.GetByteArrayValue(); } },
                { "signer_list", n => { SignerList = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubBulkSignerList>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubBulkSignerList.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signing_redirect_url", n => { SigningRedirectUrl = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "template_ids", n => { TemplateIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "test_mode", n => { TestMode = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_decline", AllowDecline);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>("ccs", Ccs);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>("custom_fields", CustomFields);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestBulkCreateEmbeddedWithTemplateRequest_metadata>("metadata", Metadata);
            writer.WriteByteArrayValue("signer_file", SignerFile);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubBulkSignerList>("signer_list", SignerList);
            writer.WriteStringValue("signing_redirect_url", SigningRedirectUrl);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("template_ids", TemplateIds);
            writer.WriteBoolValue("test_mode", TestMode);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
