// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// An array of form field objects containing the name, value, and type of each textbox or checkmark field filled in by the signers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignatureRequestResponseDataBase : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique ID for this field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiId { get; set; }
#nullable restore
#else
        public string ApiId { get; set; }
#endif
        /// <summary>The name of the form field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A boolean value denoting if this field is required.</summary>
        public bool? Required { get; set; }
        /// <summary>The ID of the signature to which this response is linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatureId { get; set; }
#nullable restore
#else
        public string SignatureId { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase"/> and sets the default values.
        /// </summary>
        public SignatureRequestResponseDataBase()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            return mappingValue switch
            {
                "checkbox" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueCheckbox(),
                "checkbox-merge" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueCheckboxMerge(),
                "date_signed" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueDateSigned(),
                "dropdown" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueDropdown(),
                "initials" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueInitials(),
                "radio" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueRadio(),
                "signature" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueSignature(),
                "text" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueText(),
                "text-merge" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataValueTextMerge(),
                _ => new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_id", n => { ApiId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "signature_id", n => { SignatureId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_id", ApiId);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("required", Required);
            writer.WriteStringValue("signature_id", SignatureId);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
