// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubFormFieldRuleTrigger : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Must reference the `api_id` of an existing field defined within `form_fields_per_document`. Trigger and action fields and groups must belong to the same signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>&quot;Different field types allow different `operator` values:- Field type of **text**:  - **is**: exact match  - **not**: not exact match  - **match**: regular expression, without /. Example:    - OK `[a-zA-Z0-9]`    - Not OK `/[a-zA-Z0-9]/`- Field type of **dropdown**:  - **is**: exact match, single value  - **not**: not exact match, single value  - **any**: exact match, array of values.  - **none**: not exact match, array of values.- Field type of **checkbox**:  - **is**: exact match, single value  - **not**: not exact match, single value- Field type of **radio**:  - **is**: exact match, single value  - **not**: not exact match, single value&quot;</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger_operator? Operator { get; set; }
        /// <summary>&quot;**value** or **values** is required, but not both.The value to match against **operator**.- When **operator** is one of the following, **value** must be `String`:  - `is`  - `not`  - `match`Otherwise,- **checkbox**: When **type** of trigger is **checkbox**, **value** must be `0` or `1`- **radio**: When **type** of trigger is **radio**, **value** must be `1`&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>**values** or **value** is required, but not both.The values to match against **operator** when it is one of the following:- `any`- `none`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Values { get; set; }
#nullable restore
#else
        public List<string> Values { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger"/> and sets the default values.
        /// </summary>
        public SubFormFieldRuleTrigger()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "operator", n => { Operator = n.GetEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger_operator>(); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "values", n => { Values = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleTrigger_operator>("operator", Operator);
            writer.WriteStringValue("value", Value);
            writer.WriteCollectionOfPrimitiveValues<string>("values", Values);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
