// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Font family for the field.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubFormFieldsPerDocumentHyperlink_font_family
    {
        [EnumMember(Value = "helvetica")]
        #pragma warning disable CS1591
        Helvetica,
        #pragma warning restore CS1591
        [EnumMember(Value = "arial")]
        #pragma warning disable CS1591
        Arial,
        #pragma warning restore CS1591
        [EnumMember(Value = "courier")]
        #pragma warning disable CS1591
        Courier,
        #pragma warning restore CS1591
        [EnumMember(Value = "calibri")]
        #pragma warning disable CS1591
        Calibri,
        #pragma warning restore CS1591
        [EnumMember(Value = "cambria")]
        #pragma warning disable CS1591
        Cambria,
        #pragma warning restore CS1591
        [EnumMember(Value = "georgia")]
        #pragma warning disable CS1591
        Georgia,
        #pragma warning restore CS1591
        [EnumMember(Value = "times")]
        #pragma warning disable CS1591
        Times,
        #pragma warning restore CS1591
        [EnumMember(Value = "trebuchet")]
        #pragma warning disable CS1591
        Trebuchet,
        #pragma warning restore CS1591
        [EnumMember(Value = "verdana")]
        #pragma warning disable CS1591
        Verdana,
        #pragma warning restore CS1591
        [EnumMember(Value = "roboto")]
        #pragma warning disable CS1591
        Roboto,
        #pragma warning restore CS1591
        [EnumMember(Value = "robotoMono")]
        #pragma warning disable CS1591
        RobotoMono,
        #pragma warning restore CS1591
        [EnumMember(Value = "notoSans")]
        #pragma warning disable CS1591
        NotoSans,
        #pragma warning restore CS1591
        [EnumMember(Value = "notoSerif")]
        #pragma warning disable CS1591
        NotoSerif,
        #pragma warning restore CS1591
        [EnumMember(Value = "notoCJK-JP-Regular")]
        #pragma warning disable CS1591
        NotoCJKJPRegular,
        #pragma warning restore CS1591
        [EnumMember(Value = "notoHebrew-Regular")]
        #pragma warning disable CS1591
        NotoHebrewRegular,
        #pragma warning restore CS1591
        [EnumMember(Value = "notoSanThaiMerged")]
        #pragma warning disable CS1591
        NotoSanThaiMerged,
        #pragma warning restore CS1591
    }
}
