// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Each text field may contain a `validation_type` parameter. Check out the list of [validation types](https://faq.hellosign.com/hc/en-us/articles/217115577) to learn more about the possible values.**NOTE:** When using `custom_regex` you are required to pass a second parameter `validation_custom_regex` and you can optionally provide `validation_custom_regex_format_label` for the error message the user will see in case of an invalid value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubFormFieldsPerDocumentTextValidationType
    {
        [EnumMember(Value = "numbers_only")]
        #pragma warning disable CS1591
        NumbersOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "letters_only")]
        #pragma warning disable CS1591
        LettersOnly,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_number")]
        #pragma warning disable CS1591
        PhoneNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "bank_routing_number")]
        #pragma warning disable CS1591
        BankRoutingNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "bank_account_number")]
        #pragma warning disable CS1591
        BankAccountNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_address")]
        #pragma warning disable CS1591
        EmailAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "zip_code")]
        #pragma warning disable CS1591
        ZipCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "social_security_number")]
        #pragma warning disable CS1591
        SocialSecurityNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "employer_identification_number")]
        #pragma warning disable CS1591
        EmployerIdentificationNumber,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom_regex")]
        #pragma warning disable CS1591
        CustomRegex,
        #pragma warning restore CS1591
    }
}
