// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Allows requester to specify the date format (see list of allowed [formats](/api/reference/constants/#date-formats))**NOTE:** Only available for Premium and higher.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubFieldOptionsDateFormat
    {
        [EnumMember(Value = "MM / DD / YYYY")]
        #pragma warning disable CS1591
        MmDdYyyy,
        #pragma warning restore CS1591
        [EnumMember(Value = "MM - DD - YYYY")]
        #pragma warning disable CS1591
        MmDdYyyy1,
        #pragma warning restore CS1591
        [EnumMember(Value = "DD / MM / YYYY")]
        #pragma warning disable CS1591
        DdMmYyyy,
        #pragma warning restore CS1591
        [EnumMember(Value = "DD - MM - YYYY")]
        #pragma warning disable CS1591
        DdMmYyyy1,
        #pragma warning restore CS1591
        [EnumMember(Value = "YYYY / MM / DD")]
        #pragma warning disable CS1591
        YyyyMmDd,
        #pragma warning restore CS1591
        [EnumMember(Value = "YYYY - MM - DD")]
        #pragma warning disable CS1591
        YyyyMmDd1,
        #pragma warning restore CS1591
    }
}
