// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubFormFieldRuleAction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>**field_id** or **group_id** is required, but not both.Must reference the `api_id` of an existing field defined within `form_fields_per_document`.Cannot use with `group_id`. Trigger and action fields must belong to the same signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldId { get; set; }
#nullable restore
#else
        public string FieldId { get; set; }
#endif
        /// <summary>**group_id** or **field_id** is required, but not both.Must reference the ID of an existing group defined within `form_field_groups`.Cannot use with `field_id`. Trigger and action fields and groups must belong to the same signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>`true` to hide the target field when rule is satisfied, otherwise `false`.</summary>
        public bool? Hidden { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction"/> and sets the default values.
        /// </summary>
        public SubFormFieldRuleAction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field_id", n => { FieldId = n.GetStringValue(); } },
                { "group_id", n => { GroupId = n.GetStringValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field_id", FieldId);
            writer.WriteStringValue("group_id", GroupId);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldRuleAction_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
