// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// This allows the requester to specify field options for a signature request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubFieldOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allows requester to specify the date format (see list of allowed [formats](/api/reference/constants/#date-formats))**NOTE:** Only available for Premium and higher.</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions_date_format? DateFormat { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions"/> and sets the default values.
        /// </summary>
        public SubFieldOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date_format", n => { DateFormat = n.GetEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions_date_format>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions_date_format>("date_format", DateFormat);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
