// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Changes the form view setting experienced by the signer. Supported versions are: - `disabled` - Form view is disabled, and the signer cannot change it - `enabled` - Form view is disabled initially, the signer can turn it on using a toggle - `enabled_by_default` - Form view is enabled initially. The signer car turn it off using a toggle - `forced` - Form view is enabled initially. The signer cannot change it, the toggle is hidden.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubSignerExperience_form_view
    {
        [EnumMember(Value = "disabled")]
        #pragma warning disable CS1591
        Disabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "enabled")]
        #pragma warning disable CS1591
        Enabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "enabled_by_default")]
        #pragma warning disable CS1591
        Enabled_by_default,
        #pragma warning restore CS1591
        [EnumMember(Value = "forced")]
        #pragma warning disable CS1591
        Forced,
        #pragma warning restore CS1591
    }
}
