// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// An array of elements and values serialized to a string, to be used to customize the app&apos;s signer page. (Only applies to some API plans)Take a look at our [white labeling guide](https://developers.hellosign.com/api/reference/premium-branding/) to learn more.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubWhiteLabelingOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The header_background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderBackgroundColor { get; set; }
#nullable restore
#else
        public string HeaderBackgroundColor { get; set; }
#endif
        /// <summary>The legal_version property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions_legal_version? LegalVersion { get; set; }
        /// <summary>The link_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkColor { get; set; }
#nullable restore
#else
        public string LinkColor { get; set; }
#endif
        /// <summary>The page_background_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageBackgroundColor { get; set; }
#nullable restore
#else
        public string PageBackgroundColor { get; set; }
#endif
        /// <summary>The primary_button_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryButtonColor { get; set; }
#nullable restore
#else
        public string PrimaryButtonColor { get; set; }
#endif
        /// <summary>The primary_button_color_hover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryButtonColorHover { get; set; }
#nullable restore
#else
        public string PrimaryButtonColorHover { get; set; }
#endif
        /// <summary>The primary_button_text_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryButtonTextColor { get; set; }
#nullable restore
#else
        public string PrimaryButtonTextColor { get; set; }
#endif
        /// <summary>The primary_button_text_color_hover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryButtonTextColorHover { get; set; }
#nullable restore
#else
        public string PrimaryButtonTextColorHover { get; set; }
#endif
        /// <summary>Resets white labeling options to defaults. Only useful when updating an API App.</summary>
        public bool? ResetToDefault { get; set; }
        /// <summary>The secondary_button_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryButtonColor { get; set; }
#nullable restore
#else
        public string SecondaryButtonColor { get; set; }
#endif
        /// <summary>The secondary_button_color_hover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryButtonColorHover { get; set; }
#nullable restore
#else
        public string SecondaryButtonColorHover { get; set; }
#endif
        /// <summary>The secondary_button_text_color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryButtonTextColor { get; set; }
#nullable restore
#else
        public string SecondaryButtonTextColor { get; set; }
#endif
        /// <summary>The secondary_button_text_color_hover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondaryButtonTextColorHover { get; set; }
#nullable restore
#else
        public string SecondaryButtonTextColorHover { get; set; }
#endif
        /// <summary>The text_color1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextColor1 { get; set; }
#nullable restore
#else
        public string TextColor1 { get; set; }
#endif
        /// <summary>The text_color2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextColor2 { get; set; }
#nullable restore
#else
        public string TextColor2 { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions"/> and sets the default values.
        /// </summary>
        public SubWhiteLabelingOptions()
        {
            AdditionalData = new Dictionary<string, object>();
            HeaderBackgroundColor = "#1a1a1a";
            LegalVersion = global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions_legal_version.Terms1;
            LinkColor = "#0061FE";
            PageBackgroundColor = "#f7f8f9";
            PrimaryButtonColor = "#0061FE";
            PrimaryButtonColorHover = "#0061FE";
            PrimaryButtonTextColor = "#ffffff";
            PrimaryButtonTextColorHover = "#ffffff";
            SecondaryButtonColor = "#ffffff";
            SecondaryButtonColorHover = "#ffffff";
            SecondaryButtonTextColor = "#0061FE";
            SecondaryButtonTextColorHover = "#0061FE";
            TextColor1 = "#808080";
            TextColor2 = "#ffffff";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "header_background_color", n => { HeaderBackgroundColor = n.GetStringValue(); } },
                { "legal_version", n => { LegalVersion = n.GetEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions_legal_version>(); } },
                { "link_color", n => { LinkColor = n.GetStringValue(); } },
                { "page_background_color", n => { PageBackgroundColor = n.GetStringValue(); } },
                { "primary_button_color", n => { PrimaryButtonColor = n.GetStringValue(); } },
                { "primary_button_color_hover", n => { PrimaryButtonColorHover = n.GetStringValue(); } },
                { "primary_button_text_color", n => { PrimaryButtonTextColor = n.GetStringValue(); } },
                { "primary_button_text_color_hover", n => { PrimaryButtonTextColorHover = n.GetStringValue(); } },
                { "reset_to_default", n => { ResetToDefault = n.GetBoolValue(); } },
                { "secondary_button_color", n => { SecondaryButtonColor = n.GetStringValue(); } },
                { "secondary_button_color_hover", n => { SecondaryButtonColorHover = n.GetStringValue(); } },
                { "secondary_button_text_color", n => { SecondaryButtonTextColor = n.GetStringValue(); } },
                { "secondary_button_text_color_hover", n => { SecondaryButtonTextColorHover = n.GetStringValue(); } },
                { "text_color1", n => { TextColor1 = n.GetStringValue(); } },
                { "text_color2", n => { TextColor2 = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("header_background_color", HeaderBackgroundColor);
            writer.WriteEnumValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubWhiteLabelingOptions_legal_version>("legal_version", LegalVersion);
            writer.WriteStringValue("link_color", LinkColor);
            writer.WriteStringValue("page_background_color", PageBackgroundColor);
            writer.WriteStringValue("primary_button_color", PrimaryButtonColor);
            writer.WriteStringValue("primary_button_color_hover", PrimaryButtonColorHover);
            writer.WriteStringValue("primary_button_text_color", PrimaryButtonTextColor);
            writer.WriteStringValue("primary_button_text_color_hover", PrimaryButtonTextColorHover);
            writer.WriteBoolValue("reset_to_default", ResetToDefault);
            writer.WriteStringValue("secondary_button_color", SecondaryButtonColor);
            writer.WriteStringValue("secondary_button_color_hover", SecondaryButtonColorHover);
            writer.WriteStringValue("secondary_button_text_color", SecondaryButtonTextColor);
            writer.WriteStringValue("secondary_button_text_color_hover", SecondaryButtonTextColorHover);
            writer.WriteStringValue("text_color1", TextColor1);
            writer.WriteStringValue("text_color2", TextColor2);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
