// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// Contains information about the templates you and your team have created.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TemplateResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>An array of the Accounts that can use this Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseAccount>? Accounts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseAccount> Accounts { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Signer attachments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment> Attachments { get; set; }
#endif
        /// <summary>Indicates whether edit rights have been granted to you by the owner (always `true` if that&apos;s you).</summary>
        public bool? CanEdit { get; set; }
        /// <summary>An array of the designated CC roles that must be specified when sending a SignatureRequest using this Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseCCRole>? CcRoles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseCCRole> CcRoles { get; set; }
#endif
        /// <summary>Deprecated. Use `custom_fields` inside the [documents](https://developers.hellosign.com/api/reference/operation/templateGet/#!c=200&amp;path=template/documents&amp;t=response) array instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentCustomFieldBase>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentCustomFieldBase> CustomFields { get; set; }
#endif
        /// <summary>An array describing each document associated with this Template. Includes form field data for each document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocument>? Documents { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocument> Documents { get; set; }
#endif
        /// <summary>`true` if you are the owner of this template, `false` if it&apos;s been shared with you by a team member.</summary>
        public bool? IsCreator { get; set; }
        /// <summary>`true` if this template was created using an embedded flow, `false` if it was created on our website. Will be `null` when you are not the creator of the Template.</summary>
        public bool? IsEmbedded { get; set; }
        /// <summary>Indicates whether the template is locked.If `true`, then the template was created outside your quota and can only be used in `test_mode`.If `false`, then the template is within your quota and can be used to create signature requests.</summary>
        public bool? IsLocked { get; set; }
        /// <summary>The default message that will be sent to signers when using this Template to send a SignatureRequest. This can be overridden when sending the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The metadata attached to the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse_metadata Metadata { get; set; }
#endif
        /// <summary>Deprecated. Use `form_fields` inside the [documents](https://developers.hellosign.com/api/reference/operation/templateGet/#!c=200&amp;path=template/documents&amp;t=response) array instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentFormFieldBase>? NamedFormFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentFormFieldBase> NamedFormFields { get; set; }
#endif
        /// <summary>Configuration options for modifying the settings of the signer application. Supports changing the form view behavior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience? SignerExperience { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience SignerExperience { get; set; }
#endif
        /// <summary>An array of the designated signer roles that must be specified when sending a SignatureRequest using this Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseSignerRole>? SignerRoles { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseSignerRole> SignerRoles { get; set; }
#endif
        /// <summary>The id of the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>The title of the Template. This will also be the default subject of the message sent to signers when using this Template to send a SignatureRequest. This can be overridden when sending the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Time the template was last updated.</summary>
        public int? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse"/> and sets the default values.
        /// </summary>
        public TemplateResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accounts", n => { Accounts = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseAccount>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseAccount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "can_edit", n => { CanEdit = n.GetBoolValue(); } },
                { "cc_roles", n => { CcRoles = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseCCRole>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseCCRole.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentCustomFieldBase>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentCustomFieldBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "documents", n => { Documents = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocument>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocument.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_creator", n => { IsCreator = n.GetBoolValue(); } },
                { "is_embedded", n => { IsEmbedded = n.GetBoolValue(); } },
                { "is_locked", n => { IsLocked = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse_metadata.CreateFromDiscriminatorValue); } },
                { "named_form_fields", n => { NamedFormFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentFormFieldBase>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentFormFieldBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signer_experience", n => { SignerExperience = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience.CreateFromDiscriminatorValue); } },
                { "signer_roles", n => { SignerRoles = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseSignerRole>(global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseSignerRole.CreateFromDiscriminatorValue)?.AsList(); } },
                { "template_id", n => { TemplateId = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseAccount>("accounts", Accounts);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>("attachments", Attachments);
            writer.WriteBoolValue("can_edit", CanEdit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseCCRole>("cc_roles", CcRoles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentCustomFieldBase>("custom_fields", CustomFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocument>("documents", Documents);
            writer.WriteBoolValue("is_creator", IsCreator);
            writer.WriteBoolValue("is_embedded", IsEmbedded);
            writer.WriteBoolValue("is_locked", IsLocked);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponse_metadata>("metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseDocumentFormFieldBase>("named_form_fields", NamedFormFields);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience>("signer_experience", SignerExperience);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.TemplateResponseSignerRole>("signer_roles", SignerRoles);
            writer.WriteStringValue("template_id", TemplateId);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
