// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Signature_request.List
{
    /// <summary>
    /// Builds and executes requests for operations under \signature_request\list
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/signature_request/list{?account_id*,page*,page_size*,query*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/signature_request/list{?account_id*,page*,page_size*,query*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of SignatureRequests that you can access. This includes SignatureRequests you have sent as well as received, but not ones that you have been CCed on.Take a look at our [search guide](/api/reference/search/) to learn more about querying signature requests.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.DropboxSign.OpenApiClient.Models.ErrorResponse">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "4XX", global::Soenneker.DropboxSign.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestListResponse>(requestInfo, global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of SignatureRequests that you can access. This includes SignatureRequests you have sent as well as received, but not ones that you have been CCed on.Take a look at our [search guide](/api/reference/search/) to learn more about querying signature requests.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.DropboxSign.OpenApiClient.Signature_request.List.ListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of SignatureRequests that you can access. This includes SignatureRequests you have sent as well as received, but not ones that you have been CCed on.Take a look at our [search guide](/api/reference/search/) to learn more about querying signature requests.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetQueryParameters 
        {
            /// <summary>Which account to return SignatureRequests for. Must be a team member. Use `all` to indicate all team members. Defaults to your account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("account_id")]
            public string? AccountId { get; set; }
#nullable restore
#else
            [QueryParameter("account_id")]
            public string AccountId { get; set; }
#endif
            /// <summary>Which page number of the SignatureRequest List to return. Defaults to `1`.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Number of objects to be returned per page. Must be between `1` and `100`. Default is `20`.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>String that includes search terms and/or fields to be used to filter the SignatureRequest objects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
