// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri
{
    /// <summary>
    /// Builds and executes requests for operations under \template\files_as_data_uri
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Files_as_data_uriRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.template.files_as_data_uri.item collection</summary>
        /// <param name="position">The id of the template files to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Item.WithTemplate_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Item.WithTemplate_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("template_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Item.WithTemplate_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Files_as_data_uriRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Files_as_data_uriRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/template/files_as_data_uri", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Template.Files_as_data_uri.Files_as_data_uriRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Files_as_data_uriRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/template/files_as_data_uri", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
