// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Embedded.Edit_url;
using Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Embedded
{
    /// <summary>
    /// Builds and executes requests for operations under \embedded
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmbeddedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The edit_url property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Embedded.Edit_url.Edit_urlRequestBuilder Edit_url
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Embedded.Edit_url.Edit_urlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sign_url property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Sign_urlRequestBuilder Sign_url
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Sign_urlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Embedded.EmbeddedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbeddedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/embedded", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Embedded.EmbeddedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EmbeddedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/embedded", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
