// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Fax.Files;
using Soenneker.DropboxSign.OpenApiClient.Fax.Item;
using Soenneker.DropboxSign.OpenApiClient.Fax.List;
using Soenneker.DropboxSign.OpenApiClient.Fax.Send;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Fax
{
    /// <summary>
    /// Builds and executes requests for operations under \fax
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FaxRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.List.ListRequestBuilder List
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Fax.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The send property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.Send.SendRequestBuilder Send
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Fax.Send.SendRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.fax.item collection</summary>
        /// <param name="position">Fax ID</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.Item.WithFax_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.Item.WithFax_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fax_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Fax.Item.WithFax_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.FaxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FaxRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fax", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.FaxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FaxRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fax", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
