// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url
{
    /// <summary>
    /// Builds and executes requests for operations under \signature_request\files_as_file_url
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Files_as_file_urlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.signature_request.files_as_file_url.item collection</summary>
        /// <param name="position">The id of the SignatureRequest to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Item.WithSignature_request_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Item.WithSignature_request_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("signature_request_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Item.WithSignature_request_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Files_as_file_urlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Files_as_file_urlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/signature_request/files_as_file_url", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Files_as_file_url.Files_as_file_urlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Files_as_file_urlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/signature_request/files_as_file_url", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
