// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Signature_request.Files.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFile_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "pdf")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
        [EnumMember(Value = "zip")]
        #pragma warning disable CS1591
        Zip,
        #pragma warning restore CS1591
    }
}
