// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url
{
    /// <summary>
    /// Builds and executes requests for operations under \embedded\sign_url
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sign_urlRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.embedded.sign_url.item collection</summary>
        /// <param name="position">The id of the signature to get a signature url for.</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Item.WithSignature_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Item.WithSignature_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("signature_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Item.WithSignature_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Sign_urlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sign_urlRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/embedded/sign_url", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Embedded.Sign_url.Sign_urlRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sign_urlRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/embedded/sign_url", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
