// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.DropboxSign.OpenApiClient.Account;
using Soenneker.DropboxSign.OpenApiClient.Api_app;
using Soenneker.DropboxSign.OpenApiClient.Bulk_send_job;
using Soenneker.DropboxSign.OpenApiClient.Embedded;
using Soenneker.DropboxSign.OpenApiClient.Fax;
using Soenneker.DropboxSign.OpenApiClient.Fax_line;
using Soenneker.DropboxSign.OpenApiClient.Oauth;
using Soenneker.DropboxSign.OpenApiClient.Report;
using Soenneker.DropboxSign.OpenApiClient.Signature_request;
using Soenneker.DropboxSign.OpenApiClient.Team;
using Soenneker.DropboxSign.OpenApiClient.Template;
using Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DropboxSignOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Account.AccountRequestBuilder Account
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The api_app property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Api_app.Api_appRequestBuilder Api_app
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Api_app.Api_appRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bulk_send_job property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Bulk_send_jobRequestBuilder Bulk_send_job
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Bulk_send_jobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The embedded property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Embedded.EmbeddedRequestBuilder Embedded
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Embedded.EmbeddedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fax property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.FaxRequestBuilder Fax
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Fax.FaxRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fax_line property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax_line.Fax_lineRequestBuilder Fax_line
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Fax_line.Fax_lineRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The report property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Report.ReportRequestBuilder Report
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Report.ReportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signature_request property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Signature_requestRequestBuilder Signature_request
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Signature_request.Signature_requestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Team.TeamRequestBuilder Team
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Team.TeamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The template property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Template.TemplateRequestBuilder Template
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Template.TemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unclaimed_draft property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Unclaimed_draftRequestBuilder Unclaimed_draft
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Unclaimed_draftRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.DropboxSignOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DropboxSignOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.hellosign.com/v3";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
