// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend
{
    /// <summary>
    /// Builds and executes requests for operations under \unclaimed_draft\edit_and_resend
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Edit_and_resendRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.unclaimed_draft.edit_and_resend.item collection</summary>
        /// <param name="position">The ID of the signature request to edit and resend.</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Item.WithSignature_request_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Item.WithSignature_request_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("signature_request_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Item.WithSignature_request_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Edit_and_resendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Edit_and_resendRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unclaimed_draft/edit_and_resend", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Unclaimed_draft.Edit_and_resend.Edit_and_resendRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Edit_and_resendRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/unclaimed_draft/edit_and_resend", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
