// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Fax_line.Area_codes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCountryQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        CA,
        #pragma warning restore CS1591
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        US,
        #pragma warning restore CS1591
        [EnumMember(Value = "UK")]
        #pragma warning disable CS1591
        UK,
        #pragma warning restore CS1591
    }
}
