// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Country of the area code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FaxLineCreateRequest_country
    {
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        CA,
        #pragma warning restore CS1591
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        US,
        #pragma warning restore CS1591
        [EnumMember(Value = "UK")]
        #pragma warning disable CS1591
        UK,
        #pragma warning restore CS1591
    }
}
