// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ReportResponse_report_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "user_activity")]
        #pragma warning disable CS1591
        User_activity,
        #pragma warning restore CS1591
        [EnumMember(Value = "document_status")]
        #pragma warning disable CS1591
        Document_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "sms_activity")]
        #pragma warning disable CS1591
        Sms_activity,
        #pragma warning restore CS1591
    }
}
