// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SignatureRequestSendWithTemplateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allows signers to decline to sign a document if `true`. Defaults to `false`.</summary>
        public bool? AllowDecline { get; set; }
        /// <summary>Add CC email recipients. Required when a CC role exists for the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>? Ccs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC> Ccs { get; set; }
#endif
        /// <summary>Client id of the app to associate with the signature request. Used to apply the branding and callback url defined for the app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>An array defining values and options for custom fields. Required when a custom field exists in the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField> CustomFields { get; set; }
#endif
        /// <summary>Use `files[]` to indicate the uploaded file(s) to send for signature.This endpoint requires either **files** or **file_urls[]**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<byte[]>? Files { get; set; }
#nullable restore
#else
        public List<byte[]> Files { get; set; }
#endif
        /// <summary>Use `file_urls[]` to have Dropbox Sign download the file(s) to send for signature.This endpoint requires either **files** or **file_urls[]**, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FileUrls { get; set; }
#nullable restore
#else
        public List<string> FileUrls { get; set; }
#endif
        /// <summary>Send with a value of `true` if you wish to enable[electronic identification (eID)](https://www.hellosign.com/features/electronic-id),which requires the signer to verify their identity with an eID provider to sign a document.&lt;br&gt;**NOTE:** You need the eID add-on to use this feature. Please [contact sales](https://sign.dropbox.com/form/contact-sales) for more information. Cannot be used in `test_mode`. Only works on requests with one signer.</summary>
        public bool? IsEid { get; set; }
        /// <summary>Send with a value of `true` if you wish to enable[Qualified Electronic Signatures](https://www.hellosign.com/features/qualified-electronic-signatures) (QES),which requires a face-to-face call to verify the signer&apos;s identity.&lt;br&gt;**NOTE:** QES is only available on the Premium API plan as an add-on purchase.Cannot be used in `test_mode`. Only works on requests with one signer.</summary>
        [Obsolete("")]
        public bool? IsQualifiedSignature { get; set; }
        /// <summary>The custom message in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Key-value data that should be attached to the signature request. This metadata is included in all API responses and events involving the signature request. For example, use the metadata field to store a signer&apos;s order number for look up when receiving events for the signature request.Each request can include up to 10 metadata keys (or 50 nested metadata keys), with key names up to 40 characters long and values up to 1000 characters long.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest_metadata Metadata { get; set; }
#endif
        /// <summary>Configuration options for modifying the settings of the signer application. Supports changing the form view behavior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience? SignerExperience { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience SignerExperience { get; set; }
#endif
        /// <summary>Add Signers to your Templated-based Signature Request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestTemplateSigner>? Signers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestTemplateSigner> Signers { get; set; }
#endif
        /// <summary>This allows the requester to specify the types allowed for creating a signature.**NOTE:** If `signing_options` are not defined in the request, the allowed types will default to those specified in the account settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions? SigningOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions SigningOptions { get; set; }
#endif
        /// <summary>The URL you want signers redirected to after they successfully sign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningRedirectUrl { get; set; }
#nullable restore
#else
        public string SigningRedirectUrl { get; set; }
#endif
        /// <summary>The subject in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Use `template_ids` to create a SignatureRequest from one or more templates, in the order in which the template will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TemplateIds { get; set; }
#nullable restore
#else
        public List<string> TemplateIds { get; set; }
#endif
        /// <summary>Whether this is a test, the signature request will not be legally binding if set to `true`. Defaults to `false`.</summary>
        public bool? TestMode { get; set; }
        /// <summary>The title you want to assign to the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest"/> and sets the default values.
        /// </summary>
        public SignatureRequestSendWithTemplateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_decline", n => { AllowDecline = n.GetBoolValue(); } },
                { "ccs", n => { Ccs = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC.CreateFromDiscriminatorValue)?.AsList(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "file_urls", n => { FileUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "files", n => { Files = n.GetCollectionOfPrimitiveValues<byte[]>()?.AsList(); } },
                { "is_eid", n => { IsEid = n.GetBoolValue(); } },
                { "is_qualified_signature", n => { IsQualifiedSignature = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest_metadata.CreateFromDiscriminatorValue); } },
                { "signer_experience", n => { SignerExperience = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience.CreateFromDiscriminatorValue); } },
                { "signers", n => { Signers = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestTemplateSigner>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestTemplateSigner.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signing_options", n => { SigningOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions.CreateFromDiscriminatorValue); } },
                { "signing_redirect_url", n => { SigningRedirectUrl = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "template_ids", n => { TemplateIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "test_mode", n => { TestMode = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_decline", AllowDecline);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>("ccs", Ccs);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>("custom_fields", CustomFields);
            writer.WriteCollectionOfPrimitiveValues<byte[]>("files", Files);
            writer.WriteCollectionOfPrimitiveValues<string>("file_urls", FileUrls);
            writer.WriteBoolValue("is_eid", IsEid);
            writer.WriteBoolValue("is_qualified_signature", IsQualifiedSignature);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSendWithTemplateRequest_metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignerExperience>("signer_experience", SignerExperience);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSignatureRequestTemplateSigner>("signers", Signers);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>("signing_options", SigningOptions);
            writer.WriteStringValue("signing_redirect_url", SigningRedirectUrl);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("template_ids", TemplateIds);
            writer.WriteBoolValue("test_mode", TestMode);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
