// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// Contains information about a signature request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SignatureRequestResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Signer attachments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment> Attachments { get; set; }
#endif
        /// <summary>The ID of the Bulk Send job which sent the signature request, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BulkSendJobId { get; set; }
#nullable restore
#else
        public string BulkSendJobId { get; set; }
#endif
        /// <summary>A list of email addresses that were CCed on the SignatureRequest. They will receive a copy of the final PDF once all the signers have signed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CcEmailAddresses { get; set; }
#nullable restore
#else
        public List<string> CcEmailAddresses { get; set; }
#endif
        /// <summary>Time the signature request was created.</summary>
        public int? CreatedAt { get; set; }
        /// <summary>An array of Custom Field objects containing the name and type of each custom field.* Text Field uses `SignatureRequestResponseCustomFieldText`* Checkbox Field uses `SignatureRequestResponseCustomFieldCheckbox`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseCustomFieldBase>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseCustomFieldBase> CustomFields { get; set; }
#endif
        /// <summary>The URL where the requester and the signers can view the current status of the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DetailsUrl { get; set; }
#nullable restore
#else
        public string DetailsUrl { get; set; }
#endif
        /// <summary>The time when the signature request will expire unsigned signatures. See [Signature Request Expiration Date](https://developers.hellosign.com/docs/signature-request/expiration/) for details.</summary>
        public int? ExpiresAt { get; set; }
        /// <summary>The URL where a copy of the request&apos;s documents can be downloaded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilesUrl { get; set; }
#nullable restore
#else
        public string FilesUrl { get; set; }
#endif
        /// <summary>The path where the completed document can be downloaded</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinalCopyUri { get; set; }
#nullable restore
#else
        public string FinalCopyUri { get; set; }
#endif
        /// <summary>Whether or not an error occurred (either during the creation of the SignatureRequest or during one of the signings).</summary>
        public bool? HasError { get; set; }
        /// <summary>Whether or not the SignatureRequest has been fully executed by all signers.</summary>
        public bool? IsComplete { get; set; }
        /// <summary>Whether or not the SignatureRequest has been declined by a signer.</summary>
        public bool? IsDeclined { get; set; }
        /// <summary>The custom message in the email that was initially sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The metadata attached to the signature request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse_metadata Metadata { get; set; }
#endif
        /// <summary>Default Label for account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalTitle { get; set; }
#nullable restore
#else
        public string OriginalTitle { get; set; }
#endif
        /// <summary>The email address of the initiator of the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequesterEmailAddress { get; set; }
#nullable restore
#else
        public string RequesterEmailAddress { get; set; }
#endif
        /// <summary>An array of form field objects containing the name, value, and type of each textbox or checkmark field filled in by the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase>? ResponseData { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase> ResponseData { get; set; }
#endif
        /// <summary>The id of the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatureRequestId { get; set; }
#nullable restore
#else
        public string SignatureRequestId { get; set; }
#endif
        /// <summary>An array of signature objects, 1 for each signer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures>? Signatures { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures> Signatures { get; set; }
#endif
        /// <summary>Configuration options for modifying the settings of the signer application. Supports changing the form view behavior.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience? SignerExperience { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience SignerExperience { get; set; }
#endif
        /// <summary>The URL you want the signer redirected to after they successfully sign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningRedirectUrl { get; set; }
#nullable restore
#else
        public string SigningRedirectUrl { get; set; }
#endif
        /// <summary>The URL where a signer, after authenticating, can sign the documents. This should only be used by users with existing Dropbox Sign accounts as they will be required to log in before signing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningUrl { get; set; }
#nullable restore
#else
        public string SigningUrl { get; set; }
#endif
        /// <summary>The subject in the email that was initially sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Templates IDs used in this SignatureRequest (if any).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TemplateIds { get; set; }
#nullable restore
#else
        public List<string> TemplateIds { get; set; }
#endif
        /// <summary>Whether this is a test signature request. Test requests have no legal value. Defaults to `false`.</summary>
        public bool? TestMode { get; set; }
        /// <summary>The title the specified Account uses for the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse"/> and sets the default values.
        /// </summary>
        public SignatureRequestResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bulk_send_job_id", n => { BulkSendJobId = n.GetStringValue(); } },
                { "cc_email_addresses", n => { CcEmailAddresses = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetIntValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseCustomFieldBase>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseCustomFieldBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "details_url", n => { DetailsUrl = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetIntValue(); } },
                { "files_url", n => { FilesUrl = n.GetStringValue(); } },
                { "final_copy_uri", n => { FinalCopyUri = n.GetStringValue(); } },
                { "has_error", n => { HasError = n.GetBoolValue(); } },
                { "is_complete", n => { IsComplete = n.GetBoolValue(); } },
                { "is_declined", n => { IsDeclined = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse_metadata.CreateFromDiscriminatorValue); } },
                { "original_title", n => { OriginalTitle = n.GetStringValue(); } },
                { "requester_email_address", n => { RequesterEmailAddress = n.GetStringValue(); } },
                { "response_data", n => { ResponseData = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signature_request_id", n => { SignatureRequestId = n.GetStringValue(); } },
                { "signatures", n => { Signatures = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signer_experience", n => { SignerExperience = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience>(global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience.CreateFromDiscriminatorValue); } },
                { "signing_redirect_url", n => { SigningRedirectUrl = n.GetStringValue(); } },
                { "signing_url", n => { SigningUrl = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "template_ids", n => { TemplateIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "test_mode", n => { TestMode = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseAttachment>("attachments", Attachments);
            writer.WriteStringValue("bulk_send_job_id", BulkSendJobId);
            writer.WriteCollectionOfPrimitiveValues<string>("cc_email_addresses", CcEmailAddresses);
            writer.WriteIntValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseCustomFieldBase>("custom_fields", CustomFields);
            writer.WriteStringValue("details_url", DetailsUrl);
            writer.WriteIntValue("expires_at", ExpiresAt);
            writer.WriteStringValue("files_url", FilesUrl);
            writer.WriteStringValue("final_copy_uri", FinalCopyUri);
            writer.WriteBoolValue("has_error", HasError);
            writer.WriteBoolValue("is_complete", IsComplete);
            writer.WriteBoolValue("is_declined", IsDeclined);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponse_metadata>("metadata", Metadata);
            writer.WriteStringValue("original_title", OriginalTitle);
            writer.WriteStringValue("requester_email_address", RequesterEmailAddress);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseDataBase>("response_data", ResponseData);
            writer.WriteStringValue("signature_request_id", SignatureRequestId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestResponseSignatures>("signatures", Signatures);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SignatureRequestSignerExperience>("signer_experience", SignerExperience);
            writer.WriteStringValue("signing_redirect_url", SigningRedirectUrl);
            writer.WriteStringValue("signing_url", SigningUrl);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("template_ids", TemplateIds);
            writer.WriteBoolValue("test_mode", TestMode);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
