// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>
    /// &quot;The fields that should appear on the document, expressed as an array of objects. (For more details you can read about it here: [Using Form Fields per Document](/docs/openapi/form-fields-per-document).)**NOTE:** Fields like **text**, **dropdown**, **checkbox**, **radio**, and **hyperlink** have additional required and optional parameters. Check out the list of [additional parameters](/api/reference/constants/#form-fields-per-document) for these field types.* Text Field use `SubFormFieldsPerDocumentText`* Dropdown Field use `SubFormFieldsPerDocumentDropdown`* Hyperlink Field use `SubFormFieldsPerDocumentHyperlink`* Checkbox Field use `SubFormFieldsPerDocumentCheckbox`* Radio Field use `SubFormFieldsPerDocumentRadio`* Signature Field use `SubFormFieldsPerDocumentSignature`* Date Signed Field use `SubFormFieldsPerDocumentDateSigned`* Initials Field use `SubFormFieldsPerDocumentInitials`* Text Merge Field use `SubFormFieldsPerDocumentTextMerge`* Checkbox Merge Field use `SubFormFieldsPerDocumentCheckboxMerge`&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubFormFieldsPerDocumentBase : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An identifier for the field that is unique across all documents in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiId { get; set; }
#nullable restore
#else
        public string ApiId { get; set; }
#endif
        /// <summary>Represents the integer index of the `file` or `file_url` document the field should be attached to.</summary>
        public int? DocumentIndex { get; set; }
        /// <summary>Size of the field in pixels.</summary>
        public int? Height { get; set; }
        /// <summary>Display name for the field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Page in the document where the field should be placed (requires documents be PDF files).- When the page number parameter is supplied, the API will use the new coordinate system.- Check out the differences between both [coordinate systems](https://faq.hellosign.com/hc/en-us/articles/217115577) and how to use them.</summary>
        public int? Page { get; set; }
        /// <summary>Whether this field is required.</summary>
        public bool? Required { get; set; }
        /// <summary>Signer index identified by the offset in the signers parameter (0-based indexing), indicating which signer should fill out the field.**NOTE:** To set the value of the field as the preparer you must set this to `me_now`**NOTE:** If type is `text-merge` or `checkbox-merge`, you must set this to sender in order to use pre-filled data.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Signer { get; set; }
#nullable restore
#else
        public string Signer { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Size of the field in pixels.</summary>
        public int? Width { get; set; }
        /// <summary>Location coordinates of the field in pixels.</summary>
        public int? X { get; set; }
        /// <summary>Location coordinates of the field in pixels.</summary>
        public int? Y { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase"/> and sets the default values.
        /// </summary>
        public SubFormFieldsPerDocumentBase()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            return mappingValue switch
            {
                "checkbox" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentCheckbox(),
                "checkbox-merge" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentCheckboxMerge(),
                "date_signed" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentDateSigned(),
                "dropdown" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentDropdown(),
                "hyperlink" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentHyperlink(),
                "initials" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentInitials(),
                "radio" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentRadio(),
                "signature" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentSignature(),
                "text" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentText(),
                "text-merge" => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentTextMerge(),
                _ => new global::Soenneker.DropboxSign.OpenApiClient.Models.SubFormFieldsPerDocumentBase(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_id", n => { ApiId = n.GetStringValue(); } },
                { "document_index", n => { DocumentIndex = n.GetIntValue(); } },
                { "height", n => { Height = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "signer", n => { Signer = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
                { "x", n => { X = n.GetIntValue(); } },
                { "y", n => { Y = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("api_id", ApiId);
            writer.WriteIntValue("document_index", DocumentIndex);
            writer.WriteIntValue("height", Height);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("page", Page);
            writer.WriteBoolValue("required", Required);
            writer.WriteStringValue("signer", Signer);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("width", Width);
            writer.WriteIntValue("x", X);
            writer.WriteIntValue("y", Y);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
