// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SubOAuth_scopes
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "request_signature")]
        #pragma warning disable CS1591
        Request_signature,
        #pragma warning restore CS1591
        [EnumMember(Value = "basic_account_info")]
        #pragma warning disable CS1591
        Basic_account_info,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_access")]
        #pragma warning disable CS1591
        Account_access,
        #pragma warning restore CS1591
        [EnumMember(Value = "signature_request_access")]
        #pragma warning disable CS1591
        Signature_request_access,
        #pragma warning restore CS1591
        [EnumMember(Value = "template_access")]
        #pragma warning disable CS1591
        Template_access,
        #pragma warning restore CS1591
        [EnumMember(Value = "team_access")]
        #pragma warning disable CS1591
        Team_access,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_app_access")]
        #pragma warning disable CS1591
        Api_app_access,
        #pragma warning restore CS1591
    }
}
