// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>Specifies the feature used with the `sms_phone_number`. Default `authentication`.If `authentication`, signer is sent a verification code via SMS that is required to access the document.If `delivery`, a link to complete the signature request is delivered via SMS (_and_ email).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubSignatureRequestSigner_sms_phone_number_type
    {
        [EnumMember(Value = "authentication")]
        #pragma warning disable CS1591
        Authentication,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivery")]
        #pragma warning disable CS1591
        Delivery,
        #pragma warning restore CS1591
    }
}
