// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SubWhiteLabelingOptions_legal_version
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "terms1")]
        #pragma warning disable CS1591
        Terms1,
        #pragma warning restore CS1591
        [EnumMember(Value = "terms2")]
        #pragma warning disable CS1591
        Terms2,
        #pragma warning restore CS1591
    }
}
