// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>A role member will take in a new Team.**NOTE:** This parameter is used only if `team_id` is provided.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamAddMemberRequest_role
    {
        [EnumMember(Value = "Member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "Developer")]
        #pragma warning disable CS1591
        Developer,
        #pragma warning restore CS1591
        [EnumMember(Value = "Team Manager")]
        #pragma warning disable CS1591
        TeamManager,
        #pragma warning restore CS1591
        [EnumMember(Value = "Admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
    }
}
