// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    /// <summary>The type of unclaimed draft to create. Use `send_document` to create a claimable file, and `request_signature` for a claimable signature request. If the type is `request_signature` then signers name and email_address are not optional.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UnclaimedDraftCreateRequest_type
    {
        [EnumMember(Value = "send_document")]
        #pragma warning disable CS1591
        Send_document,
        #pragma warning restore CS1591
        [EnumMember(Value = "request_signature")]
        #pragma warning disable CS1591
        Request_signature,
        #pragma warning restore CS1591
    }
}
