// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnclaimedDraftCreateEmbeddedWithTemplateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This allows the requester to specify whether the user is allowed to provide email addresses to CC when claiming the draft.</summary>
        public bool? AllowCcs { get; set; }
        /// <summary>Allows signers to decline to sign a document if `true`. Defaults to `false`.</summary>
        public bool? AllowDecline { get; set; }
        /// <summary>Allows signers to reassign their signature requests to other signers if set to `true`. Defaults to `false`.**NOTE:** Only available for Premium plan and higher.</summary>
        public bool? AllowReassign { get; set; }
        /// <summary>Add CC email recipients. Required when a CC role exists for the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>? Ccs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC> Ccs { get; set; }
#endif
        /// <summary>Client id of the app used to create the draft. Used to apply the branding and callback url defined for the app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>An array defining values and options for custom fields. Required when a custom field exists in the Template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField> CustomFields { get; set; }
#endif
        /// <summary>This allows the requester to specify editor options when a preparing a document</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubEditorOptions? EditorOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubEditorOptions EditorOptions { get; set; }
#endif
        /// <summary>This allows the requester to specify field options for a signature request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions? FieldOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions FieldOptions { get; set; }
#endif
        /// <summary>Use `files[]` to append additional files to the signature request being created from the template. Dropbox Sign will parse the files for [text tags](https://app.hellosign.com/api/textTagsWalkthrough) and append it to the signature request. Text tags for signers not on the template(s) will be ignored.**files** or **file_urls[]** is required, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<byte[]>? Files { get; set; }
#nullable restore
#else
        public List<byte[]> Files { get; set; }
#endif
        /// <summary>Use file_urls[] to append additional files to the signature request being created from the template. Dropbox Sign will download the file, then parse it for [text tags](https://app.hellosign.com/api/textTagsWalkthrough), and append to the signature request. Text tags for signers not on the template(s) will be ignored.**files** or **file_urls[]** is required, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? FileUrls { get; set; }
#nullable restore
#else
        public List<string> FileUrls { get; set; }
#endif
        /// <summary>Provide users the ability to review/edit the template signer roles.</summary>
        public bool? ForceSignerRoles { get; set; }
        /// <summary>Provide users the ability to review/edit the template subject and message.</summary>
        public bool? ForceSubjectMessage { get; set; }
        /// <summary>The request from this draft will not automatically send to signers post-claim if set to 1. Requester must [release](/api/reference/operation/signatureRequestReleaseHold/) the request from hold when ready to send. Defaults to `false`.</summary>
        public bool? HoldRequest { get; set; }
        /// <summary>The request created from this draft will also be signable in embedded mode if set to `true`. Defaults to `false`.</summary>
        public bool? IsForEmbeddedSigning { get; set; }
        /// <summary>The custom message in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>Key-value data that should be attached to the signature request. This metadata is included in all API responses and events involving the signature request. For example, use the metadata field to store a signer&apos;s order number for look up when receiving events for the signature request.Each request can include up to 10 metadata keys (or 50 nested metadata keys), with key names up to 40 characters long and values up to 1000 characters long.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest_metadata Metadata { get; set; }
#endif
        /// <summary>Controls whether [auto fill fields](https://faq.hellosign.com/hc/en-us/articles/360051467511-Auto-Fill-Fields) can automatically populate a signer&apos;s information during signing.**NOTE:** Keep your signer&apos;s information safe by ensuring that the _signer on your signature request is the intended party_ before using this feature.</summary>
        public bool? PopulateAutoFillFields { get; set; }
        /// <summary>&quot;This allows the requester to enable the preview experience (i.e. does not allow the requester&apos;s end user to add any additional fields via the editor).- `preview_only=true`: Allows requesters to enable the preview only experience.- `preview_only=false`: Allows requesters to disable the preview only experience.**NOTE:** This parameter overwrites `show_preview=1` (if set).&quot;</summary>
        public bool? PreviewOnly { get; set; }
        /// <summary>The email address of the user that should be designated as the requester of this draft.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequesterEmailAddress { get; set; }
#nullable restore
#else
        public string RequesterEmailAddress { get; set; }
#endif
        /// <summary>The URL you want signers redirected to after they successfully request a signature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestingRedirectUrl { get; set; }
#nullable restore
#else
        public string RequestingRedirectUrl { get; set; }
#endif
        /// <summary>&quot;This allows the requester to enable the editor/preview experience.- `show_preview=true`: Allows requesters to enable the editor/preview experience.- `show_preview=false`: Allows requesters to disable the editor/preview experience.&quot;</summary>
        public bool? ShowPreview { get; set; }
        /// <summary>When only one step remains in the signature request process and this parameter is set to `false` then the progress stepper will be hidden.</summary>
        public bool? ShowProgressStepper { get; set; }
        /// <summary>Add Signers to your Templated-based Signature Request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubUnclaimedDraftTemplateSigner>? Signers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.DropboxSign.OpenApiClient.Models.SubUnclaimedDraftTemplateSigner> Signers { get; set; }
#endif
        /// <summary>This allows the requester to specify the types allowed for creating a signature.**NOTE:** If `signing_options` are not defined in the request, the allowed types will default to those specified in the account settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions? SigningOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions SigningOptions { get; set; }
#endif
        /// <summary>The URL you want signers redirected to after they successfully sign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningRedirectUrl { get; set; }
#nullable restore
#else
        public string SigningRedirectUrl { get; set; }
#endif
        /// <summary>Disables the &quot;Me (Now)&quot; option for the person preparing the document. Does not work with type `send_document`. Defaults to `false`.</summary>
        public bool? SkipMeNow { get; set; }
        /// <summary>The subject in the email that will be sent to the signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Use `template_ids` to create a SignatureRequest from one or more templates, in the order in which the templates will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TemplateIds { get; set; }
#nullable restore
#else
        public List<string> TemplateIds { get; set; }
#endif
        /// <summary>Whether this is a test, the signature request created from this draft will not be legally binding if set to `true`. Defaults to `false`.</summary>
        public bool? TestMode { get; set; }
        /// <summary>The title you want to assign to the SignatureRequest.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest"/> and sets the default values.
        /// </summary>
        public UnclaimedDraftCreateEmbeddedWithTemplateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_ccs", n => { AllowCcs = n.GetBoolValue(); } },
                { "allow_decline", n => { AllowDecline = n.GetBoolValue(); } },
                { "allow_reassign", n => { AllowReassign = n.GetBoolValue(); } },
                { "ccs", n => { Ccs = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC.CreateFromDiscriminatorValue)?.AsList(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField.CreateFromDiscriminatorValue)?.AsList(); } },
                { "editor_options", n => { EditorOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubEditorOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubEditorOptions.CreateFromDiscriminatorValue); } },
                { "field_options", n => { FieldOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions.CreateFromDiscriminatorValue); } },
                { "file_urls", n => { FileUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "files", n => { Files = n.GetCollectionOfPrimitiveValues<byte[]>()?.AsList(); } },
                { "force_signer_roles", n => { ForceSignerRoles = n.GetBoolValue(); } },
                { "force_subject_message", n => { ForceSubjectMessage = n.GetBoolValue(); } },
                { "hold_request", n => { HoldRequest = n.GetBoolValue(); } },
                { "is_for_embedded_signing", n => { IsForEmbeddedSigning = n.GetBoolValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest_metadata>(global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest_metadata.CreateFromDiscriminatorValue); } },
                { "populate_auto_fill_fields", n => { PopulateAutoFillFields = n.GetBoolValue(); } },
                { "preview_only", n => { PreviewOnly = n.GetBoolValue(); } },
                { "requester_email_address", n => { RequesterEmailAddress = n.GetStringValue(); } },
                { "requesting_redirect_url", n => { RequestingRedirectUrl = n.GetStringValue(); } },
                { "show_preview", n => { ShowPreview = n.GetBoolValue(); } },
                { "show_progress_stepper", n => { ShowProgressStepper = n.GetBoolValue(); } },
                { "signers", n => { Signers = n.GetCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubUnclaimedDraftTemplateSigner>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubUnclaimedDraftTemplateSigner.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signing_options", n => { SigningOptions = n.GetObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>(global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions.CreateFromDiscriminatorValue); } },
                { "signing_redirect_url", n => { SigningRedirectUrl = n.GetStringValue(); } },
                { "skip_me_now", n => { SkipMeNow = n.GetBoolValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "template_ids", n => { TemplateIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "test_mode", n => { TestMode = n.GetBoolValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allow_ccs", AllowCcs);
            writer.WriteBoolValue("allow_decline", AllowDecline);
            writer.WriteBoolValue("allow_reassign", AllowReassign);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCC>("ccs", Ccs);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubCustomField>("custom_fields", CustomFields);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubEditorOptions>("editor_options", EditorOptions);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubFieldOptions>("field_options", FieldOptions);
            writer.WriteCollectionOfPrimitiveValues<byte[]>("files", Files);
            writer.WriteCollectionOfPrimitiveValues<string>("file_urls", FileUrls);
            writer.WriteBoolValue("force_signer_roles", ForceSignerRoles);
            writer.WriteBoolValue("force_subject_message", ForceSubjectMessage);
            writer.WriteBoolValue("hold_request", HoldRequest);
            writer.WriteBoolValue("is_for_embedded_signing", IsForEmbeddedSigning);
            writer.WriteStringValue("message", Message);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.UnclaimedDraftCreateEmbeddedWithTemplateRequest_metadata>("metadata", Metadata);
            writer.WriteBoolValue("populate_auto_fill_fields", PopulateAutoFillFields);
            writer.WriteBoolValue("preview_only", PreviewOnly);
            writer.WriteStringValue("requester_email_address", RequesterEmailAddress);
            writer.WriteStringValue("requesting_redirect_url", RequestingRedirectUrl);
            writer.WriteBoolValue("show_preview", ShowPreview);
            writer.WriteBoolValue("show_progress_stepper", ShowProgressStepper);
            writer.WriteCollectionOfObjectValues<global::Soenneker.DropboxSign.OpenApiClient.Models.SubUnclaimedDraftTemplateSigner>("signers", Signers);
            writer.WriteObjectValue<global::Soenneker.DropboxSign.OpenApiClient.Models.SubSigningOptions>("signing_options", SigningOptions);
            writer.WriteStringValue("signing_redirect_url", SigningRedirectUrl);
            writer.WriteBoolValue("skip_me_now", SkipMeNow);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("template_ids", TemplateIds);
            writer.WriteBoolValue("test_mode", TestMode);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
