// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Fax_line.Area_codes
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProvinceQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "AB")]
        #pragma warning disable CS1591
        AB,
        #pragma warning restore CS1591
        [EnumMember(Value = "BC")]
        #pragma warning disable CS1591
        BC,
        #pragma warning restore CS1591
        [EnumMember(Value = "MB")]
        #pragma warning disable CS1591
        MB,
        #pragma warning restore CS1591
        [EnumMember(Value = "NB")]
        #pragma warning disable CS1591
        NB,
        #pragma warning restore CS1591
        [EnumMember(Value = "NL")]
        #pragma warning disable CS1591
        NL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NT")]
        #pragma warning disable CS1591
        NT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NS")]
        #pragma warning disable CS1591
        NS,
        #pragma warning restore CS1591
        [EnumMember(Value = "NU")]
        #pragma warning disable CS1591
        NU,
        #pragma warning restore CS1591
        [EnumMember(Value = "ON")]
        #pragma warning disable CS1591
        ON,
        #pragma warning restore CS1591
        [EnumMember(Value = "PE")]
        #pragma warning disable CS1591
        PE,
        #pragma warning restore CS1591
        [EnumMember(Value = "QC")]
        #pragma warning disable CS1591
        QC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SK")]
        #pragma warning disable CS1591
        SK,
        #pragma warning restore CS1591
        [EnumMember(Value = "YT")]
        #pragma warning disable CS1591
        YT,
        #pragma warning restore CS1591
    }
}
