// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Fax.Files.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Fax.Files
{
    /// <summary>
    /// Builds and executes requests for operations under \fax\files
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.fax.files.item collection</summary>
        /// <param name="position">Fax ID</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.Item.WithFax_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.Item.WithFax_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fax_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.Item.WithFax_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fax/files", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Fax.Files.FilesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/fax/files", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
