// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Item;
using Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.List;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DropboxSign.OpenApiClient.Bulk_send_job
{
    /// <summary>
    /// Builds and executes requests for operations under \bulk_send_job
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Bulk_send_jobRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.List.ListRequestBuilder List
        {
            get => new global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.DropboxSign.OpenApiClient.bulk_send_job.item collection</summary>
        /// <param name="position">The id of the BulkSendJob to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Item.WithBulk_send_job_ItemRequestBuilder"/></returns>
        public global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Item.WithBulk_send_job_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("bulk_send_job_id", position);
                return new global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Item.WithBulk_send_job_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Bulk_send_jobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bulk_send_jobRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bulk_send_job", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DropboxSign.OpenApiClient.Bulk_send_job.Bulk_send_jobRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Bulk_send_jobRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bulk_send_job", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
